# Generated by Django 5.0.2 on 2024-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='no title', max_length=100, null=True)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
