# Generated by Django 5.0.2 on 2024-02-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_book_isbestseller_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='some-string'),
        ),
    ]
