# Generated by Django 5.0.2 on 2024-02-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.address'),
        ),
    ]
